language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
notifications:
  email: false

services:
  - mongodb

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - echo $PATH
  - pwd
  - ls /home/travis/miniconda2/bin
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc gfortran m4 autoconf automake libtool

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy nose coverage future networkx
  - pip install pymongo
  - pip install -e "git+https://github.com/atztogo/spglib.git#egg=spglib&subdirectory=python"
  - pip install -e "git+https://github.com/z4r/python-coveralls.git#egg=coveralls"

# Run test
script:
  nosetests -v --with-cov --cover-package pychemia --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls
