language: python
python:
  - 2.7
  - 3.3
notifications:
  email: false

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - echo $PATH
  - pwd
  - ls /home/travis/miniconda2/bin
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy nose coverage future networkx
  - conda install --yes -c dan_blanchard python-coveralls nose-cov
  - conda install --yes -c jochym spglib=1.9.0

# Run test
script:
  nosetests -v --with-cov --cover-package pychemia --logging-level=INFO

# Calculate coverage
after_success:
  - coveralls
