#!/bin/bash

version=`cat pychemia/setup.json | grep version | awk -F: '{print $2}' | awk -F\" '{print $2}'`

cd docs
make html
cd ..

python3 setup.py sdist
python3 setup.py bdist_wheel

twine upload -r pypi dist/pychemia-$version-cp37-cp37m-linux_x86_64.whl 
twine upload -r pypi dist/pychemia-$version.tar.gz

